services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  api:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    #restart: on-failure:5
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
